site_name: Susan Westfall
nav:
        - About me: index.md
        - Education: education.md
        - Research Experience: researchexperience.md
        - Awards & Honors: awards.md
        - Teaching & Mentoring: work.md 
        - Scientific Community Involvement: community.md
        - Publications : publications.md

theme:
        name: null
        custom_dir: ./theme
#         palette:
#                 primary: 'deep purple'
#                 accent: 'light blue'
#         font:
#                 text: 'Hind'
#                 code: 'Roboto Mono'
# #        icon:
# #                logo: fontawesome/user-astronaut
#         feature:
#                 - tabs
markdown_extensions:
        - admonition
        - attr_list
        - toc:
            permalink: true
            permalink_title: null
